version: "3.6"


services:
  consul:
    image: ozlevka/consul-cloud:work-1
    command: -bind=192.168.1.108 -bootstrap-expect=1 -server -ui -client=0.0.0.0
    network_mode: "host"

  nginx:
    image: nginx:current
    network_mode: "host"
