---
# main playbook for running all
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    credentials_file: ./google.json
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20180509
    compute_zone: us-central1-f

  tasks:

   - name: Launch instances
     gce:
         instance_names: help-1
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "ansible@{{ project }}.iam.gserviceaccount.com"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project }}"
         zone: "{{ compute_zone }}"
         state: "{{ state }}"

