---
# main playbook for running all
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    credentials_file: ./google.json
    machine_type: g1-small
    image: ubuntu-1604-xenial-v20180509
    compute_zone: us-central1-c
    instance_names: ["manager-1"]
    spot: true

  tasks:

   - name: Launch instances
     gce:
         instance_names: "{{ ','.join(instance_names) }}"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "ansible@{{ project }}.iam.gserviceaccount.com"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project }}"
         zone: "{{ compute_zone }}"
         state: "{{ state }}"
         preemptible: "{{ spot }}"
     delegate_to: localhost
     register: gce_result



